name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Test with TypeScript
        run: "pnpm exec ts-node-esm src/index.ts"

      - name: Compile
        run: "pnpm i && pnpm webpack --mode=production"

      - name: Test with Node
        run: "node dist/bundle.js"
      
      - name: Test with QuickJS
        uses: refracturemedia/quickjs-gh-action/@v0.1.0
        with:
          mainFile: dist/bundle.js