name: Test

on:
  push:

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install + Compile + Beautify
        run: "pnpm i && pnpm webpack --mode=development && pnpm js-beautify ./dist/bundle.js --replace"

      - name: Test with TypeScript
        continue-on-error: true
        run: "pnpm exec ts-node-esm src/index.ts"

      - name: Test with Node
        continue-on-error: true
        run: "node dist/bundle.js"
      
      - name: Test with QuickJS
        uses: refracturemedia/quickjs-gh-action/@v0.1.0
        with:
          mainFile: "--unhandled-rejection dist/bundle.js"